Xacadmey/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Xacadmey.Models;
using Xacadmey.Repositary;
namespace Xacadmey.Controllers
{
    public class InstructorController : Controller
    {
        //Academy context=new Academy();
        IinstructorRepository _instructorRepository;
        ICourseRepository courseRepository;
        IDepartmentRepository departmentRepository;

        public InstructorController(IinstructorRepository iR, ICourseRepository Cr, IDepartmentRepository ID)
        {
            _instructorRepository = iR;
            courseRepository = Cr;
            departmentRepository = ID;
            
        }
        public IActionResult ReadInstructorList()
        {
            //List<Instructor> inst = context.Instructors.ToList();
            List<Instructor>insta= _instructorRepository.GetAll();
            return View(insta);
        }
        [HttpGet]
        public IActionResult CreateNewInstructor()
        {

            ViewData["DeptList"] = departmentRepository.GetAll();

            ViewData["CourseList"]=courseRepository.GetAll();
            return View();

            //    var departments = context.Departments
            //          .Select(d => new SelectListItem
            //          {
            //              Value = d.Id.ToString(), // assuming Id is the department ID
            //              Text = d.Name // assuming Name is the department name
            //          })
            //          .ToList();

            //    ViewBag.Departments = departments; 

            //    var course = context.Courses
            //         .Select(x => new SelectListItem
            //         {
            //             Value = x.Id.ToString(), // assuming Id is the department ID
            //             Text = x.Name // assuming Name is the department name
            //         })
            //         .ToList();

            //    ViewBag.CourseId =course; return View();
            //
        }
        
        [HttpPost]
        public IActionResult CreateNewInstructor(Instructor s)
        {
            if (ModelState.IsValid == true)
            {
                if (s.DepartmentId != 0&&s.CourseId!=0)
                {
                    try
                    {
                        _instructorRepository.Insert(s);
                        return RedirectToAction("ReadInstructorList");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);

                    }

                }
                else
                {
                    ModelState.AddModelError("DepartmentId", "select department");
                    ModelState.AddModelError("CourseId", "select course");
                }


            }
            ViewData["DeptList"] = departmentRepository.GetAll();
            ViewData["CourseList"] = courseRepository.GetAll();
            return View(s);

         
        }
        [HttpGet]
        public IActionResult EditInstructor(int id) {

           Instructor ss = _instructorRepository.GetById(id);
           ViewData["DeptList"] = departmentRepository.GetAll();
           ViewData["CourseList"] = courseRepository.GetAll();
            return View(ss);
        }
        [HttpPost]
        public IActionResult EditInstructor(Instructor x)
        {
            if (ModelState.IsValid == true)
            {
                if (x.DepartmentId != 0 && x.CourseId != 0)
                {
                    try
                    {
                        _instructorRepository.Update(x);
                        return RedirectToAction("ReadInstructorList");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);

                    }

                }
                else
                {
                    ModelState.AddModelError("DepartmentId", "select department");
                    ModelState.AddModelError("CourseId", "select course");
                }


            }
            ViewData["DeptList"] = departmentRepository.GetAll();
            ViewData["CourseList"] = courseRepository.GetAll();
            return View(x);
        }

        public IActionResult DeleteInstructor(int id)
        {
           
               _instructorRepository.Delete(id);

                return RedirectToAction("ReadInstructorList");
        }






        //public IActionResult GetInstrutorDetails()
        //{
        //    List<Instructor>inst_data=context.Instructors.Include(x=>x.Course).ThenInclude(p=>p.Department).ToList();

        //    return View("ShowInstructorData",inst_data);
        //}
        //public IActionResult detailbyId(int id)
        //{
        //    Instructor s = context.Instructors.FirstOrDefault(s => s.Id == id);
        //    return View("detailid",s);
            
        //}
        //public IActionResult Details()
        //{
        //    List<string> branches = new List<string>();
        //    branches.Add("assuit");
        //    branches.Add("alex");
        //    branches.Add("smart");
        //    ViewData["bran"] = branches;
        //    ViewData["msg"] = "Hello from Acadmy";
        //   Instructor stud = context.Instructors.FirstOrDefault();
        //    return View("Details", stud);

        //}
        //public IActionResult DetailsWithVM()
        //{
        //    List<string> branches = new List<string>();
        //    branches.Add("assuit");
        //    branches.Add("alex");
        //    branches.Add("smart");
           
        //    Instructor stud = context.Instructors.FirstOrDefault();
        //    Department dept= context.Departments.FirstOrDefault();
        //    InstructorWithBranchListViewModel INSVM= new InstructorWithBranchListViewModel();
        //    INSVM.InsName=stud.Name;
        //    INSVM.InsImage=stud.Image;
        //    INSVM.branches= branches;
        //    INSVM.DeptManagerName = dept.ManagerName;
        //    INSVM.temp = 5;
        //    if (INSVM.temp >0)
        //    {
        //        INSVM.color = "Red";
        //    }
        //    else
        //    {
        //        INSVM.color = "Blue";
        //    }
        //    INSVM.Msg = "Hello from vm";
        //    return View("DetailsWithVM", INSVM);

        //}
    }
}

Xacadmey/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Xacadmey.ViewModel;

namespace Xacadmey.Controllers
{
   
    public class RoleController : Controller
    {
       
        private readonly RoleManager<IdentityRole> roleManger;
        public RoleController(RoleManager<IdentityRole>roleManger)
        {
            this.roleManger=roleManger;
            
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> New(RoleViewModel newrolevm)
        {
            if (ModelState.IsValid) {
                IdentityRole role=new IdentityRole();
                role.Name = newrolevm.RoleName;
                IdentityResult result=  await roleManger.CreateAsync(role);
                if (result.Succeeded) { 
                
                 return View(new RoleViewModel());
                
                }
                foreach (var item in result.Errors)
                {

                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(newrolevm);
        }
    }
}

Xacadmey/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Xacadmey</title>
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <style>
        .colored-anchor {
            display: inline-block;
            text-align: center;
            padding: 20px;
            font-size: 24px;
            color: white;
            text-decoration: none;
        }

        .blue-bg {
            background-color: #007bff;
        }

        .green-bg {
            background-color: #28a745;
        }

        .red-bg {
            background-color: #dc3545;
        }

        .purple-bg {
            background-color: #6f42c1;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Xacadmey</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="GetInstrutorDetails">Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="New">Add Role</a>
                        </li>
                       
                    </ul>
                    <ul class="navbar-nav ">
                     
                        @if (User.Identity.IsAuthenticated == false)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="login">Login</a>
                            </li>
                           

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="logout">Welcome @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="logout">Logout</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Xacadmey - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>