Xacadmey/Models/Trainee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Xacadmey.Models
{
    public class Trainee
    {
        public int Id { get; set; }
        [Required]
        [MinLength(3,ErrorMessage ="Name must be greater than 3 letters")]
        [MaxLength(20, ErrorMessage = "Name must be less than 20 letters")]
        [UniqueName]
        public string Name { get; set; }
        [RegularExpression(@"\w+\.(jpg|png)",ErrorMessage ="Image must be jpg or png")]
        public string Image { get; set; }
        [Required]
        //[RegularExpression(@"(Alex|Assuit)")]
        public string Address { get; set; }
        [Required]

        public int Grade { get; set; }

        [ForeignKey("Department")]
        [Display(Name = "Department Name")]
        public int DepartmentId { get; set; }
        public virtual Department ? Department { get; set; }
    }
}

Xacadmey/Controllers/TraineeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Xacadmey.Models;
using Xacadmey.Repositary;
using Xacadmey.ViewModel;

namespace Xacadmey.Controllers
{
    public class TraineeController : Controller
    {
        // Academy context = new Academy();
        ITraineeRepository traineeRepository;

        IDepartmentRepository departmentRepository;
        public TraineeController(ITraineeRepository _TranRep,IDepartmentRepository _DeptRep)
        {
            traineeRepository = _TranRep;//new TraineeRepositary();
            departmentRepository = _DeptRep;//new DepartmentRepositary();
        }
    
         //public IActionResult TraineeCourseResult(int id, object context)
         //{
         //    try
         //    {

         //        List<CourseResult> courses = context.CourseResults.Include(x => x.Trainee).Include(y => y.Course).Where(T => T.TraineeId == id).ToList();
         //        List<TraineeGetbyidViewModel> ListOfModel = new List<TraineeGetbyidViewModel>();

         //        foreach (var course in courses) {
         //            TraineeGetbyidViewModel tranieViModel = new TraineeGetbyidViewModel();
         //            tranieViModel.TraineeDegree = course.Degree;
         //            tranieViModel.TraineeName = course.Trainee.Name;
         //            tranieViModel.CourseName = course.Course.Name;

         //            if (course.Degree > 25)
         //            {
         //                tranieViModel.Color = "green";
         //                tranieViModel.Status = "pass";
         //            }
         //            else
         //            {
         //                tranieViModel.Color = "red";
         //                tranieViModel.Status = "fail";
         //            }

         //            ListOfModel.Add(tranieViModel);

         //        }
         //        return View(ListOfModel);

         //    }
         //    catch (System.Exception ex)
         //    {

         //        throw;
         //    }
         //}
        [HttpGet]

        //public IActionResult New()
        //{
        //    // ViewData["DeptList"] = context.Departments.ToList();
        //     ViewData["DeptList"] = departmentRepositary.GetAll();
        //    return View("New");
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult SaveNew(Trainee tr)
        //{

        //    if (ModelState.IsValid == true)
        //    {
        //        if (tr.DepartmentId != 0)
        //        {


        //            try
        //            {
        //                traineeRepositary.Insert(tr);
        //                context.Traineess.Add(tr);
        //               context.SaveChanges();

        //                return RedirectToAction("Index");
        //            }
        //            catch (Exception e)
        //            {
        //                ModelState.AddModelError("", e.Message);
        //            }
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("DepartmentId", "select department");
        //        }
        //    }
        //         ViewData["DeptList"] = context.Departments.ToList();
        //        //ViewData["DeptList"] = departmentRepositary.GetAll();
        //        return View("New",tr);


        //}
        //public IActionResult Index()
        //{
        //     List<Trainee> trainees = context.Traineess.Include(X=>X.Department).ToList();
        //    //List<Trainee> trainees=traineeRepositary.GetAll();
        //    return View(trainees);
        //}
        [Authorize]
        public IActionResult ReadTraineeslist()
        {
            List<Trainee> trainees = traineeRepository.GetAll();
            return View(trainees);
        }
        [HttpGet]
        public IActionResult CreateNewTrainee()
        {
            //var department = context.Departments.
            //    Select(d => new SelectListItem
            //    {
            //        Value = d.Id.ToString(),
            //        Text = d.Name
            //    }
            //    ).ToList();
            //ViewBag.DepartmentId = department;
            ViewData["DeptList"] = departmentRepository.GetAll();

            return View();
        }
        [HttpPost]
        public IActionResult CreateNewTrainee(Trainee trainee)
        {

            if (ModelState.IsValid == true)
            {
                if (trainee.DepartmentId != 0)
                {


                    try
                    {
                        //context.Traineess.Add(trainee);
                        //context.SaveChanges();
                        traineeRepository.Insert(trainee);

                        return RedirectToAction("ReadTraineeslist");
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e.Message);
                    }
                }
                else
                {
                    ModelState.AddModelError("DepartmentId", "select department");
                }
            }
            ViewData["DeptList"] = departmentRepository.GetAll();
          //  ViewData["DeptList"] = context.Departments.ToList();
            //var department = context.Departments.
            //  Select(d => new SelectListItem
            //  {
            //      Value = d.Id.ToString(),
            //      Text = d.Name
            //  }
            //  ).ToList();
            //ViewBag.DepartmentId = department;


            return View(trainee);
          
        }
        [HttpGet]
        public IActionResult EditTrainee(int id) {


            Trainee trainee= traineeRepository.GetById(id);
            ViewData["DeptList"] = departmentRepository.GetAll();
            //Trainee trainee = context.Traineess.Find(id);

            //var department = context.Departments.
            //Select(d => new SelectListItem
            //{
            //    Value = d.Id.ToString(),
            //    Text = d.Name
            //}
            //).ToList();
            //ViewBag.DepartmentId = department;
            return View(trainee);
        }
        [HttpPost]

        public IActionResult EditTrainee(Trainee tr)
        {
            if (ModelState.IsValid == true)
            {
                if (tr.DepartmentId != 0)
                {


                    try
                    {
                        //context.Traineess.Update(tr);
                        //context.SaveChanges();
                      traineeRepository.Update(tr);

                        return RedirectToAction("ReadTraineeslist");
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e.Message);
                    }
                }
                else
                {
                    ModelState.AddModelError("DepartmentId", "select department");
                }
            }
             ViewData["DeptList"] = departmentRepository.GetAll();
            //var department = context.Departments.
            //  Select(d => new SelectListItem
            //  {
            //      Value = d.Id.ToString(),
            //      Text = d.Name
            //  }
            //  ).ToList();
               //    ViewBag.DepartmentId = department;


            return View(tr);
        }
    
        public ActionResult DeleteTrainee(int id)
        {

            //Trainee t = context.Traineess.Find(id);
            //context.Traineess.Remove(t);
            //context.SaveChanges();
            traineeRepository.Delete(id);
            return RedirectToAction("ReadTraineeslist");
        }
    }
}

Xacadmey/Views/Trainee/CreateNewTrainee.cshtml
@model Xacadmey.Models.Trainee

@{
    ViewData["Title"] = "CreateNewTrainee";
    SelectList DeptItems =
    new SelectList(ViewBag.DeptList,"Id","Name");

}

<h1>CreateNewTrainee</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewTrainee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image"type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>

           @*  <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId">
                <option value="0">select department</option>
                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div> *@
            <div class="form-group">

                <label asp-for="DepartmentId"></label>

                <select asp-items="DeptItems" asp-for="DepartmentId" class="form-control">
                 <option value="0">select department</option>

                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        @section Scripts{
            @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
            <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        }
         </div>
</div>

<div>
    <a asp-action="ReadTraineeslist">Back to List</a>
</div>

Xacadmey/Views/Trainee/DeleteTrainee.cshtml
@model Xacadmey.Models.Trainee

@{
    ViewData["Title"] = "DeleteTrainee";
}

<h1>DeleteTrainee</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
    </dl>
    
    <form asp-action="DeleteTrainee">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ReadTraineeslist">Back to List</a>
    </form>
</div>

Xacadmey/Views/Trainee/EditTrainee.cshtml
@model Xacadmey.Models.Trainee

@{
    ViewData["Title"] = "EditTrainee";

    SelectList DeptItems =
    new SelectList(ViewBag.DeptList,"Id","Name");

}

<h1>EditTrainee</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditTrainee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
           @*  <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId">
                    <option value="0">select department</option>
                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div> *@
            <div class="form-group">

                <label asp-for="DepartmentId"></label>

                <select asp-items="DeptItems" asp-for="DepartmentId" class="form-control">
                 <option value="0">select department</option>

                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        @section Scripts {
            @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
            <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        }
    </div>
</div>

<div>
    <a asp-action="ReadTraineeslist">Back to List</a>
</div>

Xacadmey/Views/Trainee/Index.cshtml
@model List<Trainee>
<a asp-controller="Trainee" asp-action="New">Add New Trainee</a>

<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Image</th>
        <th>Department</th>
        <th>Grade</th>
    </tr>
    @foreach (var i in Model)
    {


        <tr>
            <td>@i.Name</td>
            <td>@i.Address</td>
            <td>@i.Image</td>
            <td>@i.Department.Name</td>
            <td>@i.Grade</td>
        </tr>
    }

</table>

Xacadmey/Views/Trainee/New.cshtml
@model Trainee
@{
    ViewData["Title"] = "New";
    SelectList DeptItems =
    new SelectList(ViewBag.DeptList,"Id","Name");

}
<form method="post" asp-action="SaveNew" asp-controller="Trainee">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div>
    <label asp-for="Name"></label>
    <input  asp-for="Name"class="form-control"/>
    <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Image"></label>
        <input asp-for="Image"type="file" class="form-control" />

    </div>

    <div>
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />

    </div>
    <div>

        <label asp-for="DepartmentId"></label>
        
        <select asp-items="DeptItems" asp-for="DepartmentId" class="form-control">
        <option value="0">select department</option>
  
        </select>
        <span asp-validation-for="DepartmentId" class="text-danger"></span>

    </div>
    <br />
    <div>
        <label asp-for="Grade"></label>
        <input asp-for="Grade" class="form-control" />

    </div>




    <div>
        <input type="submit" value="Create" class="btn btn-success" />
    </div>

   
</form>

Xacadmey/Views/Trainee/ReadTraineeslist.cshtml
@model List<Trainee>
@{
    ViewData["Title"] = "ReadTraineeslist";
}

<h1>ReadTraineeslist</h1>


    <a href="/Trainee/CreateNewTrainee" class="btn btn-primary">Add</a>
    @* <a asp-controller="Trainee" asp-action="New">Add New Trainee</a> *@

    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Image</th>
            <th>Department</th>
            <th>Grade</th>
        </tr>
        @foreach (var i in Model)
        {


            <tr>
                <td>@i.Name</td>
                <td>@i.Address</td>
                <td>@i.Image</td>
                <td>@i.Department.Name</td>
                <td>@i.Grade</td>
                <td ><a href="/Trainee/EditTrainee/@i.Id"class="colored-anchor green-bg">Edit</a>
                    <a href="/Trainee/DeleteTrainee/@i.Id" class="colored-anchor red-bg">Delete</a>
                </td>
            </tr>
        }

    </table>

Xacadmey/Views/Trainee/TraineeCourseResult.cshtml
@model List<TraineeGetbyidViewModel>;

<table class="table table-bordered table-hover">
    <tr>
        <th>Trainee Name</th>
        <th>Course Name</th>
        <th>Degree</th>
        <th>Status</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.TraineeName</td>
            <td>@item.CourseName</td>
            <td>@item.TraineeDegree</td>
            <td style="background-color:@item.Color">@item.Status</td>

        </tr>
    }

</table>